<Project>
  <PropertyGroup>
    <BaseOutputPath>D:\BIM-S_TestArtifacts\build\$(MSBuildProjectName)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>D:\BIM-S_TestArtifacts\build\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
